spring:
  datasource:
    url: jdbc:mysql://localhost:3306/weather?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        show-sql: true
        ddl-auto: create
        format_sql: true

logging:
  level:
    org.hibernate: info
    org.hibernate.SQL: debug
    org.hibernate.type: trace

jwt:
  secret: thisismyweatherdataprojectthisismyweatherdataprojectthisismyweatherdataproject